In [3]:
# 실습. Numpy 모듈 사용해보기2
import numpy as np

arr = np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
arr1 = np.unique(arr)
print(arr1)

print(np.max(arr1))
print(np.min(arr1))
print(np.mean(arr1))
print(np.sum(arr1))
print(np.median(arr))


[  1   2   3   4   5   7   8   9  10  11  24 100]
100
1
15.333333333333334
184
5.0


In [32]:
# 실습. Numpy 모듈 사용해보기3
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
print(x)

print(f"최대: {np.max(x[:,0])}, 최소: {np.min(x[:,0])}, 평균: {np.mean(x[:,0])}")

print(f"2행 합: {np.sum(x[1,:])}")
a = np.argsort(arr)
print(arr[a])
a_rev = arr[::-1]
print(arr[a[::-1]])

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
최대: 0, 최소: -99, 평균: -66.0
2행 합: -283
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
