In [1]:
import numpy as np
x = np.array([3,1,2])
print(x)
print(type(x))
print(type([3,1,2]))

[3 1 2]
<class 'numpy.ndarray'>
<class 'list'>


In [6]:
c = [[1],[1,2]]
d = np.array([[1,1],[1,2]]) # 모든 배열의 차원이 같아야 한다

for x,y in d:
    print(x,y)

1 1
1 2


In [7]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 7613-4D4E

 c:\Users\bjy80\Documents\data ���͸�

2024-12-13  ���� 12:18    <DIR>          .
2024-12-13  ���� 12:16    <DIR>          ..
2024-12-13  ���� 12:18                 0 numpy.ipynb
               1�� ����                   0 ����Ʈ
               2�� ���͸�  51,946,487,808 ����Ʈ ����


In [9]:
x = np.array(([1.0, 2.0, 3.0]))
y = np.array(([2.0, 4.0, 6.0]))

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [12]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)


(3,)
float64
(2, 2)
[1. 2. 3.]


In [13]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


In [14]:
print(a.shape)

(3, 2)


In [16]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)

3


In [17]:
print(a.shape)

(3, 2, 1)


In [18]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.shape)


(3, 2, 2)


In [19]:
np.dot(4,2)

8

In [25]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1, ndar2)

24

In [23]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [27]:
ndar1 = np.array([[1],[3]])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1, ndar2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [29]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [30]:
ndarr = np.array([[1,2],[2,3],[3,4]]) # 3x2
ndarr.reshape(2,3)


array([[1, 2, 2],
       [3, 3, 4]])

In [33]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [34]:
np.random.randint(5, size = (2,4))

array([[3, 4, 1, 1],
       [4, 2, 1, 0]])

In [35]:
np.random.rand(2,4)

array([[0.52065615, 0.69466001, 0.79662418, 0.38004516],
       [0.28098137, 0.57704937, 0.24789819, 0.13780491]])

In [36]:
rng = np.random.default_rng()

In [37]:
rng.random()

0.34576430391905133

In [38]:
rng.integers(0, 10, (2,4))

array([[6, 3, 5, 2],
       [6, 3, 4, 7]], dtype=int64)

In [39]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [42]:
ndarr[ndarr > 1] # 1차원으로 출력 특정한 값 뽑아내기

array([6, 3, 5, 2, 4])

In [41]:
ndarr[[[ True, False],
       [ True, False],
       [False, False]]]

array([6, 5])

In [43]:
ndarr[1:]

array([[5, 2],
       [4, 1]])